POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Paco Porras",
    "number": "987-654-321"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{}